Vagrant.configure("2") do |config|
  config.vm.define "mysql-server" do |vm|
    vm.vm.box = "bento/ubuntu-22.04"
    vm.vm.hostname = "mysql-server"
    vm.vm.network "public_network", type: "dhcp", bridge: "Intel(R) Ethernet Connection (4) I219-LM"
    vm.vm.provision "shell", path: "./scripts/install.sh"

  end

end